// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Planb.Enrollments.Infrastructure.Persistence;

#nullable disable

namespace Planb.Enrollments.Infrastructure.Migrations
{
    [DbContext(typeof(EnrollmentsDbContext))]
    [Migration("20260515141909_InitialEnrollmentsSchema")]
    partial class InitialEnrollmentsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("enrollments")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Planb.Enrollments.Domain.EnrollmentRecords.EnrollmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalMethod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("approval_method");

                    b.Property<Guid?>("CommissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("commission_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("grade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid?>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId")
                        .HasDatabaseName("ix_enrollment_records_student");

                    b.HasIndex("StudentProfileId", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ux_enrollment_records_student_subject_equivalencia")
                        .HasFilter("approval_method = 'Equivalencia'");

                    b.HasIndex("StudentProfileId", "SubjectId", "TermId")
                        .IsUnique()
                        .HasDatabaseName("ux_enrollment_records_student_subject_term");

                    b.ToTable("enrollment_records", "enrollments", t =>
                        {
                            t.HasCheckConstraint("ck_enrollment_records_cursada_requires_commission_and_term", "approval_method NOT IN ('Cursada','Promocion','Final') OR (commission_id IS NOT NULL AND term_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_enrollment_records_equivalencia_no_commission_no_term", "approval_method IS DISTINCT FROM 'Equivalencia' OR (commission_id IS NULL AND term_id IS NULL)");

                            t.HasCheckConstraint("ck_enrollment_records_final_libre_term_only", "approval_method IS DISTINCT FROM 'FinalLibre' OR (commission_id IS NULL AND term_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_enrollment_records_grade_range", "grade IS NULL OR (grade >= 0 AND grade <= 10)");

                            t.HasCheckConstraint("ck_enrollment_records_status_approval_method_consistency", "(status = 'Aprobada' AND approval_method IS NOT NULL) OR (status <> 'Aprobada' AND approval_method IS NULL)");

                            t.HasCheckConstraint("ck_enrollment_records_status_grade_consistency", "(status IN ('Aprobada','Regular') AND grade IS NOT NULL) OR (status IN ('Cursando','Reprobada','Abandonada') AND grade IS NULL)");
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("wolverine_incoming_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.ToTable("wolverine_outgoing_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
