// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Planb.Identity.Domain.Users;
using Planb.Identity.Infrastructure.Persistence;

#nullable disable

namespace Planb.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260627195053_AddTeacherProfileVerification")]
    partial class AddTeacherProfileVerification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "identity", "user_role", new[] { "admin", "member", "moderator", "university_staff" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Planb.Identity.Domain.TeacherProfiles.TeacherProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InstitutionalEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("institutional_email");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VerificationMethod")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("verification_method");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId")
                        .IsUnique()
                        .HasDatabaseName("ux_teacher_profiles_teacher_verified")
                        .HasFilter("verified_at IS NOT NULL");

                    b.HasIndex("UserId", "TeacherId")
                        .IsUnique()
                        .HasDatabaseName("ux_teacher_profiles_user_teacher");

                    b.ToTable("teacher_profiles", "identity");
                });

            modelBuilder.Entity("Planb.Identity.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<Guid?>("DisabledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("disabled_by");

                    b.Property<string>("DisabledReason")
                        .HasColumnType("text")
                        .HasColumnName("disabled_reason");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<UserRole>("Role")
                        .HasColumnType("identity.user_role")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email_active")
                        .HasFilter("expired_at IS NULL AND deactivated_at IS NULL");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("Planb.Identity.Domain.Users.UserDeletionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EmailHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("email_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EmailHash")
                        .HasDatabaseName("ix_user_deletion_log_email_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_deletion_log_user_id");

                    b.ToTable("user_deletion_log", "identity");
                });

            modelBuilder.Entity("Planb.Identity.Domain.Users.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowTeacherContact")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_teacher_contact");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("language");

                    b.Property<bool>("NotificationsEmail")
                        .HasColumnType("boolean")
                        .HasColumnName("notifications_email");

                    b.Property<bool>("NotificationsInApp")
                        .HasColumnType("boolean")
                        .HasColumnName("notifications_in_app");

                    b.Property<bool>("NotifyAcademicCalendar")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_academic_calendar");

                    b.Property<bool>("NotifyDraftPromotionNudge")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_draft_promotion_nudge");

                    b.Property<bool>("NotifyNewReviewInFollowed")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_new_review_in_followed");

                    b.Property<bool>("NotifyReviewResponse")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_review_response");

                    b.Property<bool>("ShowDisplayNameInReviews")
                        .HasColumnType("boolean")
                        .HasColumnName("show_display_name_in_reviews");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("theme");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_settings_user_id");

                    b.ToTable("user_settings", "identity");
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("wolverine_incoming_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.ToTable("wolverine_outgoing_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Planb.Identity.Domain.TeacherProfiles.TeacherProfile", b =>
                {
                    b.OwnsMany("Planb.Identity.Domain.Users.VerificationToken", "Tokens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset?>("ConsumedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("consumed_at");

                            b1.Property<DateTimeOffset>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("expires_at");

                            b1.Property<DateTimeOffset?>("InvalidatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("invalidated_at");

                            b1.Property<DateTimeOffset>("IssuedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("issued_at");

                            b1.Property<string>("Purpose")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("purpose");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("token");

                            b1.Property<Guid>("teacher_profile_id")
                                .HasColumnType("uuid")
                                .HasColumnName("teacher_profile_id");

                            b1.HasKey("Id");

                            b1.HasIndex("Token")
                                .IsUnique()
                                .HasDatabaseName("ux_teacher_verification_tokens_token");

                            b1.HasIndex("teacher_profile_id")
                                .HasDatabaseName("ix_teacher_verification_tokens_profile_id");

                            b1.ToTable("teacher_verification_tokens", "identity");

                            b1.WithOwner()
                                .HasForeignKey("teacher_profile_id");
                        });

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Planb.Identity.Domain.Users.User", b =>
                {
                    b.OwnsMany("Planb.Identity.Domain.Users.StudentProfile", "StudentProfiles", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("CareerId")
                                .HasColumnType("uuid")
                                .HasColumnName("career_id");

                            b1.Property<Guid>("CareerPlanId")
                                .HasColumnType("uuid")
                                .HasColumnName("career_plan_id");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("display_name");

                            b1.Property<int>("EnrollmentYear")
                                .HasColumnType("integer")
                                .HasColumnName("enrollment_year");

                            b1.Property<string>("Legajo")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("legajo");

                            b1.Property<bool>("RegularStudent")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("regular_student");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("status");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<int?>("YearOfStudy")
                                .HasColumnType("integer")
                                .HasColumnName("year_of_study");

                            b1.Property<Guid>("user_id")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.HasKey("Id");

                            b1.HasIndex("user_id")
                                .HasDatabaseName("ix_student_profiles_user_id");

                            b1.HasIndex("user_id", "CareerId")
                                .IsUnique()
                                .HasDatabaseName("ux_student_profiles_user_career_active")
                                .HasFilter("status = 'Active'");

                            b1.ToTable("student_profiles", "identity");

                            b1.WithOwner()
                                .HasForeignKey("user_id");
                        });

                    b.OwnsMany("Planb.Identity.Domain.Users.VerificationToken", "Tokens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset?>("ConsumedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("consumed_at");

                            b1.Property<DateTimeOffset>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("expires_at");

                            b1.Property<DateTimeOffset?>("InvalidatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("invalidated_at");

                            b1.Property<DateTimeOffset>("IssuedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("issued_at");

                            b1.Property<string>("Purpose")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("purpose");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("token");

                            b1.Property<Guid>("user_id")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.HasKey("Id");

                            b1.HasIndex("Token")
                                .IsUnique()
                                .HasDatabaseName("ux_verification_tokens_token");

                            b1.HasIndex("user_id")
                                .HasDatabaseName("ix_verification_tokens_user_id");

                            b1.ToTable("verification_tokens", "identity");

                            b1.WithOwner()
                                .HasForeignKey("user_id");
                        });

                    b.Navigation("StudentProfiles");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
