// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Planb.Reviews.Infrastructure.Persistence;

#nullable disable

namespace Planb.Reviews.Infrastructure.Migrations
{
    [DbContext(typeof(ReviewsDbContext))]
    [Migration("20260623014015_AddReviewVotes")]
    partial class AddReviewVotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reviews")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Planb.Reviews.Domain.AuditLog.ReviewAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_user_id");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId", "OccurredAt")
                        .HasDatabaseName("ix_review_audit_log_review_id_occurred_at");

                    b.ToTable("review_audit_log", "reviews");
                });

            modelBuilder.Entity("Planb.Reviews.Domain.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedReason")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("deleted_reason");

                    b.Property<short>("DifficultyRating")
                        .HasColumnType("smallint")
                        .HasColumnName("difficulty_rating");

                    b.Property<Guid>("DocenteResenadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("docente_resenado_id");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrollment_id");

                    b.Property<decimal?>("FinalGrade")
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("final_grade");

                    b.Property<short?>("HoursPerWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("hours_per_week");

                    b.Property<short>("OverallRating")
                        .HasColumnType("smallint")
                        .HasColumnName("overall_rating");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectText")
                        .HasColumnType("text")
                        .HasColumnName("subject_text");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("TeacherText")
                        .HasColumnType("text")
                        .HasColumnName("teacher_text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("WouldRecommendCourse")
                        .HasColumnType("boolean")
                        .HasColumnName("would_recommend_course");

                    b.Property<bool>("WouldRetakeTeacher")
                        .HasColumnType("boolean")
                        .HasColumnName("would_retake_teacher");

                    b.HasKey("Id");

                    b.HasIndex("DocenteResenadoId")
                        .HasDatabaseName("ix_reviews_docente_resenado");

                    b.HasIndex("EnrollmentId")
                        .IsUnique()
                        .HasDatabaseName("ux_reviews_enrollment")
                        .HasFilter("status <> 'Deleted'");

                    b.ToTable("reviews", "reviews", t =>
                        {
                            t.HasCheckConstraint("ck_reviews_at_least_one_text", "subject_text IS NOT NULL OR teacher_text IS NOT NULL");

                            t.HasCheckConstraint("ck_reviews_difficulty_rating_range", "difficulty_rating BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_reviews_final_grade_range", "final_grade IS NULL OR (final_grade >= 0 AND final_grade <= 10)");

                            t.HasCheckConstraint("ck_reviews_hours_per_week_range", "hours_per_week IS NULL OR (hours_per_week >= 0 AND hours_per_week <= 30)");

                            t.HasCheckConstraint("ck_reviews_overall_rating_range", "overall_rating BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Planb.Reviews.Domain.Votes.ReviewVote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsHelpful")
                        .HasColumnType("boolean")
                        .HasColumnName("is_helpful");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VoterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("voter_user_id");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId")
                        .HasDatabaseName("ix_review_votes_review_id");

                    b.HasIndex("ReviewId", "VoterUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_review_votes_review_voter");

                    b.ToTable("review_votes", "reviews");
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("wolverine_incoming_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.ToTable("wolverine_outgoing_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
