// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Planb.Reviews.Infrastructure.Persistence;

#nullable disable

namespace Planb.Reviews.Infrastructure.Migrations
{
    [DbContext(typeof(ReviewsDbContext))]
    [Migration("20260826205829_AddCourseReviews")]
    partial class AddCourseReviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reviews")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Planb.Reviews.Domain.AuditLog.ReviewAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_user_id");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId", "OccurredAt")
                        .HasDatabaseName("ix_review_audit_log_review_id_occurred_at");

                    b.ToTable("review_audit_log", "reviews");
                });

            modelBuilder.Entity("Planb.Reviews.Domain.Catalog.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.Property<short>("Version")
                        .HasColumnType("smallint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Code", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_instruments_code_version");

                    b.ToTable("instruments", "reviews");
                });

            modelBuilder.Entity("Planb.Reviews.Domain.Catalog.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Help")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("help");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Layer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("layer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("subject");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_items_code");

                    b.ToTable("items", "reviews");
                });

            modelBuilder.Entity("Planb.Reviews.Domain.CourseReviews.CourseReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("ChairId")
                        .HasColumnType("uuid")
                        .HasColumnName("chair_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FreeText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("free_text");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "SubjectId", "TermId")
                        .IsUnique()
                        .HasDatabaseName("ux_course_reviews_account_subject_term");

                    b.ToTable("course_reviews", "reviews");
                });

            modelBuilder.Entity("Planb.Reviews.Domain.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedReason")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("deleted_reason");

                    b.Property<short>("DifficultyRating")
                        .HasColumnType("smallint")
                        .HasColumnName("difficulty_rating");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrollment_id");

                    b.Property<decimal?>("FinalGrade")
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("final_grade");

                    b.Property<short?>("HoursPerWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("hours_per_week");

                    b.Property<short>("OverallRating")
                        .HasColumnType("smallint")
                        .HasColumnName("overall_rating");

                    b.Property<Guid?>("ReviewedTeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_teacher_id");

                    b.Property<string>("ReviewedTeacherName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reviewed_teacher_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectText")
                        .HasColumnType("text")
                        .HasColumnName("subject_text");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("TeacherText")
                        .HasColumnType("text")
                        .HasColumnName("teacher_text");

                    b.Property<string>("UnderReviewReason")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("under_review_reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("WouldRecommendCourse")
                        .HasColumnType("boolean")
                        .HasColumnName("would_recommend_course");

                    b.Property<bool>("WouldRetakeTeacher")
                        .HasColumnType("boolean")
                        .HasColumnName("would_retake_teacher");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_reviews_author_user_id");

                    b.HasIndex("EnrollmentId")
                        .IsUnique()
                        .HasDatabaseName("ux_reviews_enrollment")
                        .HasFilter("status <> 'Deleted'");

                    b.HasIndex("ReviewedTeacherId")
                        .HasDatabaseName("ix_reviews_reviewed_teacher");

                    b.ToTable("reviews", "reviews", t =>
                        {
                            t.HasCheckConstraint("ck_reviews_at_least_one_text", "subject_text IS NOT NULL OR teacher_text IS NOT NULL");

                            t.HasCheckConstraint("ck_reviews_difficulty_rating_range", "difficulty_rating BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_reviews_final_grade_range", "final_grade IS NULL OR (final_grade >= 0 AND final_grade <= 10)");

                            t.HasCheckConstraint("ck_reviews_hours_per_week_range", "hours_per_week IS NULL OR (hours_per_week >= 0 AND hours_per_week <= 30)");

                            t.HasCheckConstraint("ck_reviews_overall_rating_range", "overall_rating BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_reviews_subject_text_length", "subject_text IS NULL OR char_length(subject_text) BETWEEN 50 AND 2000");

                            t.HasCheckConstraint("ck_reviews_teacher_text_length", "teacher_text IS NULL OR char_length(teacher_text) BETWEEN 50 AND 2000");
                        });
                });

            modelBuilder.Entity("Planb.Reviews.Domain.Votes.ReviewVote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsHelpful")
                        .HasColumnType("boolean")
                        .HasColumnName("is_helpful");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VoterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("voter_user_id");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId")
                        .HasDatabaseName("ix_review_votes_review_id");

                    b.HasIndex("ReviewId", "VoterUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_review_votes_review_voter");

                    b.ToTable("review_votes", "reviews");
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("wolverine_incoming_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.ToTable("wolverine_outgoing_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Planb.Reviews.Domain.Catalog.Instrument", b =>
                {
                    b.OwnsMany("Planb.Reviews.Domain.Catalog.InstrumentItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("instrument_id")
                                .HasColumnType("uuid")
                                .HasColumnName("instrument_id");

                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("item_id");

                            b1.Property<short>("Order")
                                .HasColumnType("smallint")
                                .HasColumnName("order");

                            b1.HasKey("instrument_id", "ItemId");

                            b1.ToTable("instrument_items", "reviews");

                            b1.WithOwner()
                                .HasForeignKey("instrument_id");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Planb.Reviews.Domain.Catalog.Item", b =>
                {
                    b.OwnsMany("Planb.Reviews.Domain.Catalog.ItemOption", "Options", b1 =>
                        {
                            b1.Property<Guid>("item_id")
                                .HasColumnType("uuid")
                                .HasColumnName("item_id");

                            b1.Property<short>("Value")
                                .HasColumnType("smallint")
                                .HasColumnName("value");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("label");

                            b1.Property<short>("Order")
                                .HasColumnType("smallint")
                                .HasColumnName("order");

                            b1.Property<string>("Valence")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("valence");

                            b1.HasKey("item_id", "Value");

                            b1.ToTable("item_options", "reviews");

                            b1.WithOwner()
                                .HasForeignKey("item_id");
                        });

                    b.Navigation("Options");
                });

            modelBuilder.Entity("Planb.Reviews.Domain.CourseReviews.CourseReview", b =>
                {
                    b.OwnsMany("Planb.Reviews.Domain.CourseReviews.ItemAnswer", "Answers", b1 =>
                        {
                            b1.Property<Guid>("course_review_id")
                                .HasColumnType("uuid")
                                .HasColumnName("course_review_id");

                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("item_id");

                            b1.Property<short>("OptionValue")
                                .HasColumnType("smallint")
                                .HasColumnName("option_value");

                            b1.HasKey("course_review_id", "ItemId");

                            b1.ToTable("course_review_answers", "reviews");

                            b1.WithOwner()
                                .HasForeignKey("course_review_id");
                        });

                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Planb.Reviews.Domain.Reviews.Review", b =>
                {
                    b.OwnsOne("Planb.Reviews.Domain.Reviews.TeacherResponse", "Response", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("status");

                            b1.Property<Guid>("TeacherId")
                                .HasColumnType("uuid")
                                .HasColumnName("teacher_id");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("text");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<Guid>("review_id")
                                .HasColumnType("uuid")
                                .HasColumnName("review_id");

                            b1.HasKey("Id");

                            b1.HasIndex("review_id")
                                .IsUnique()
                                .HasDatabaseName("ux_teacher_responses_review");

                            b1.ToTable("teacher_responses", "reviews");

                            b1.WithOwner()
                                .HasForeignKey("review_id");
                        });

                    b.Navigation("Response");
                });
#pragma warning restore 612, 618
        }
    }
}
